name=I2SGen4_RK
version=0.0.1
license=MIT
author=Rick Kaseguma <rickkas7@rickkas7.com>
sentence=I2S (sound) support for Particle Gen 4 (RTL872x) devices
url=https://github.com/rickkas7/I2SGen4_RK
repository=https://github.com/rickkas7/I2SGen4_RK.git
architectures=*
